### ISSUE TITLE
Can't capture timings that are greater than uint16 (65535)

### ISSUE THREAD

**Issue by sweetpi** [pimatic/RFControl#6]
Like in this protocol: http://forum.pimatic.org/topic/166/quigg-protocol-for-rfcontroljs/5

I think a simple solution would be to divide all timings by a factor of 2, since the precision would be still good enough. When sending the timings by serial we could just multiply it by 2 to be backward compatible.

**Comment by Icesory** [comment]
This is a good idea. I think too it should work so. 
 
And another reason for an automatic arduino update routine

**Comment by sweetpi** [comment]
Solved with pulse_length_divider.
